export const REGISTRO_EXITOSO = " REGISTRO_EXITOSO ";
export const REGISTRO_ERROR = "REGISTRO_ERROR";
export const LOGIN_EXITOSO = "LOGIN_EXITOSO";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const USUARIO_AUTENTICADO = "USUARIO_AUTENTICADO";
export const CERRAR_SESION = "CERRAR_SESION";
export const OCULTAR_ALERTA = " OCULTAR_ALERTA ";

export const CREAR_MEDICAMENTO = "CREAR_MEDICAMENTO";
export const OBTENER_MEDICAMENTO = "OBTENER_MEDICAMENTO";
export const ELIMINAR_MEDICAMENTO = "ELIMINAR_MEDICAMENTO";
export const ACTUALIZAR_MEDICAMENTO = "ACTUALIZAR_MEDICAMENTO";
export const SELECCIONAR_MEDICAMENTO = "SELECCIONAR_MEDICAMENTO";
export const RESET_MEDICAMENTO = "RESET_MEDICAMENTO";
